package br.gov.sp.fatec.construtora.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.Date;
import java.util.Set;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "bld_building")
@AttributeOverride(name = "id", column = @Column(name = "bld_id"))
public class Building extends AutoGeneratedId {

    public Building(String address, Date constructionDate, Integer floors, ConstructionCompany constructionCompany) {
        this.setAddress(address);
        this.setConstructionDate(constructionDate);
        this.setFloors(floors);
        this.setConstructionCompanyOwner(constructionCompany);
    }

    @Column(name = "bld_address")
    private String address;

    @Column(name = "bld_construction_date")
    private Date constructionDate;

    @Column(name = "bld_floors")
    private Integer floors;

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "cmp_construction_company_id")
    private ConstructionCompany constructionCompanyOwner;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "bpe_building_per_engineer",
        joinColumns = {@JoinColumn(name = "bld_building_id")},
        inverseJoinColumns = {@JoinColumn(name = "eng_engineer_id")})
    private Set<Engineer> engineers;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "bpw_building_per_worker",
        joinColumns = {@JoinColumn(name = "bld_building_id")},
        inverseJoinColumns = {@JoinColumn(name = "eng_engineer_id")})
    private Set<Worker> workers;
}
