package br.gov.sp.fatec.construtora.entity;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;

@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "cmp_company")
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
@DiscriminatorColumn(name = "cmp_type")
@AttributeOverride(name = "id", column = @Column(name = "cmp_id"))
public abstract class Company extends AutoGeneratedId {

    public Company (String cnpj, String name) {
        this.setCnpj(cnpj);
        this.setName(name);
    }

    @Column(name = "cmp_cnpj")
    private String cnpj;

    @Column(name = "cmp_name")
    private String name;
}
