package br.gov.sp.fatec.construtora.entity;

import lombok.Getter;
import lombok.Setter;
import lombok.NoArgsConstructor;

import javax.persistence.*;
import java.util.Date;

@Getter
@Setter
@NoArgsConstructor
@Table(name = "usr_user")
@Entity
@Inheritance(strategy = InheritanceType.JOINED)
@AttributeOverride(name = "id", column = @Column(name = "usr_id"))
public abstract class User extends AutoGeneratedId {

    public User(String name, String password, Date admissionData) {
        this.setName(name);
        this.setPassword(password);
        this.setAdmissionData(admissionData);
    }

    @Column(name = "usr_name")
    private String name;

    @Column(name = "usr_password")
    private String password;

    @Column(name = "usr_admission_date")
    private Date admissionData;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cmp_headhunter_company_id")
    private HeadhunterCompany headhunterRecruiter;
}
